<template>
  <div
    class="h-screen d-flex items-center justify-center align-center flex-column w-100"
    style="background-color: #e8eef2"
  >
    <p class="text-h3 text-center mt-16">Translate your Text</p>
    <v-row class="pa-10 w-66 mx-auto h-screen mt-10">
      <!-- LEFT PANEL -->
      <v-col cols="12" md="6">
        <v-card class="pa-4" elevation="1" color="#fefefe">
          <!-- Dropdown Row -->
          <div class="d-flex align-center mb-4" style="gap: 12px">
            <v-select
              :items="languages"
              item-title="label"
              item-value="value"
              v-model="selectedLang"
              label="Translate to"
              variant="outlined"
              density="comfortable"
              style="max-width: 180px"
            />

            <v-select
              :items="models"
              item-title="label"
              item-value="value"
              v-model="selectedModel"
              label="AI Model"
              variant="outlined"
              density="comfortable"
              style="max-width: 180px"
            />
          </div>

          <div class="text-subtitle-1 mb-2">Source Text</div>

          <v-textarea
            v-model="sourceText"
            variant="plain"
            rows="8"
            class="border-sm rounded-lg px-4"
            no-resize
            placeholder="Enter text to translate."
          />

          <v-btn block class="mt-4 mx-auto" color="#3770e8" @click="translate">
            Translate
          </v-btn>
        </v-card>
      </v-col>

      <!-- RIGHT PANEL -->
      <v-col cols="12" md="6">
        <v-card class="pa-4" elevation="1">
          <div class="text-subtitle-1 mb-2">Translated Text</div>

          <v-textarea
            v-model="translatedText"
            variant="plain"
            rows="13"
            class="border-sm rounded-lg px-4 mb-4"
            no-resize
            placeholder="Translated text appears here..."
          />
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

const languages = [
  { label: "English", value: "en" },
  { label: "Slovenian", value: "sl" },
  { label: "German", value: "de" },
];

const models = [
  { label: "ChatGPT", value: "chatgpt" },
  { label: "Google Gemini", value: "gemini" },
];

// State
const selectedLang = ref("Select");
const selectedModel = ref("chatgpt");
const sourceText = ref("");
const translatedText = ref("");

// Stats
const timeMs = ref(0);
const tokens = ref(0);
const cost = ref(0);

// Fake translation function
const translate = async () => {
  const start = performance.now();

  // Simulate API call
  await new Promise((r) => setTimeout(r, 500));

  translatedText.value =
    selectedModel.value === "chatgpt"
      ? "This is the translated text generated by ChatGPT."
      : "This is the translated text generated by Google Gemini.";

  // Fake stats
  tokens.value = Math.floor(Math.random() * 150 + 50);
  cost.value = Number((tokens.value * 0.00002).toFixed(3));
  timeMs.value = Math.floor(performance.now() - start);
};
</script>

<style scoped>
.v-card {
  border-radius: 16px;
}
</style>
